// Code generated by protoc-gen-go. DO NOT EDIT.
// source: unwrap_request_evm.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UnwrapRequestEvmProto struct {
	NetworkClass         uint32   `protobuf:"varint,1,opt,name=networkClass,proto3" json:"networkClass,omitempty"`
	ChainId              uint32   `protobuf:"varint,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,3,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,4,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TransactionHash      []byte   `protobuf:"bytes,5,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	LogIndex             uint32   `protobuf:"varint,6,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
	From                 []byte   `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`
	Token                []byte   `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`
	Amount               []byte   `protobuf:"bytes,10,opt,name=amount,proto3" json:"amount,omitempty"`
	Signature            string   `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	RedeemStatus         uint32   `protobuf:"varint,12,opt,name=redeemStatus,proto3" json:"redeemStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnwrapRequestEvmProto) Reset()         { *m = UnwrapRequestEvmProto{} }
func (m *UnwrapRequestEvmProto) String() string { return proto.CompactTextString(m) }
func (*UnwrapRequestEvmProto) ProtoMessage()    {}
func (*UnwrapRequestEvmProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a195c65809385cd, []int{0}
}

func (m *UnwrapRequestEvmProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnwrapRequestEvmProto.Unmarshal(m, b)
}
func (m *UnwrapRequestEvmProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnwrapRequestEvmProto.Marshal(b, m, deterministic)
}
func (m *UnwrapRequestEvmProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnwrapRequestEvmProto.Merge(m, src)
}
func (m *UnwrapRequestEvmProto) XXX_Size() int {
	return xxx_messageInfo_UnwrapRequestEvmProto.Size(m)
}
func (m *UnwrapRequestEvmProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UnwrapRequestEvmProto.DiscardUnknown(m)
}

var xxx_messageInfo_UnwrapRequestEvmProto proto.InternalMessageInfo

func (m *UnwrapRequestEvmProto) GetNetworkClass() uint32 {
	if m != nil {
		return m.NetworkClass
	}
	return 0
}

func (m *UnwrapRequestEvmProto) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *UnwrapRequestEvmProto) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *UnwrapRequestEvmProto) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *UnwrapRequestEvmProto) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *UnwrapRequestEvmProto) GetLogIndex() uint32 {
	if m != nil {
		return m.LogIndex
	}
	return 0
}

func (m *UnwrapRequestEvmProto) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *UnwrapRequestEvmProto) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *UnwrapRequestEvmProto) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *UnwrapRequestEvmProto) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *UnwrapRequestEvmProto) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *UnwrapRequestEvmProto) GetRedeemStatus() uint32 {
	if m != nil {
		return m.RedeemStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*UnwrapRequestEvmProto)(nil), "events.UnwrapRequestEvmProto")
}

func init() { proto.RegisterFile("unwrap_request_evm.proto", fileDescriptor_0a195c65809385cd) }

var fileDescriptor_0a195c65809385cd = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0x86, 0xb3, 0x2b, 0x2c, 0x30, 0xa0, 0x26, 0x8d, 0x9a, 0x89, 0xf1, 0xb0, 0xe1, 0xb4, 0x27,
	0x3c, 0xf8, 0x06, 0x1a, 0x13, 0xb9, 0x18, 0xb3, 0xc6, 0x8b, 0x17, 0x52, 0x60, 0x04, 0xc2, 0xb6,
	0xc5, 0x76, 0xba, 0xf8, 0xd6, 0xbe, 0x82, 0x61, 0x56, 0x05, 0xbd, 0xf5, 0xff, 0xfa, 0xb5, 0x99,
	0xfc, 0x03, 0x18, 0xed, 0xd6, 0xeb, 0xcd, 0xc4, 0xd3, 0x7b, 0xa4, 0xc0, 0x13, 0xaa, 0xcd, 0x68,
	0xe3, 0x1d, 0x3b, 0x95, 0x51, 0x4d, 0x96, 0xc3, 0xf0, 0x33, 0x85, 0xf3, 0x17, 0x91, 0xca, 0xc6,
	0xb9, 0xaf, 0xcd, 0x93, 0x18, 0x43, 0x18, 0x58, 0xe2, 0xad, 0xf3, 0xeb, 0xbb, 0x4a, 0x87, 0x80,
	0x49, 0x9e, 0x14, 0xc7, 0xe5, 0x1f, 0xa6, 0x10, 0x3a, 0xb3, 0xa5, 0x5e, 0xd9, 0xf1, 0x1c, 0x53,
	0xb9, 0xfe, 0x89, 0x2a, 0x87, 0xfe, 0xb4, 0x72, 0xb3, 0xf5, 0x63, 0x34, 0x53, 0xf2, 0x78, 0x94,
	0x27, 0x45, 0xab, 0x3c, 0x44, 0xea, 0x0a, 0x7a, 0x12, 0x1f, 0x74, 0x58, 0x62, 0x2b, 0x4f, 0x8a,
	0x41, 0xb9, 0x07, 0xaa, 0x80, 0x53, 0xf6, 0xda, 0x06, 0x3d, 0xe3, 0x95, 0xb3, 0xe2, 0xb4, 0xc5,
	0xf9, 0x8f, 0xd5, 0x25, 0x74, 0x2b, 0xb7, 0x18, 0xdb, 0x39, 0x7d, 0x60, 0x26, 0x43, 0xfc, 0x66,
	0xa5, 0xa0, 0xf5, 0xe6, 0x9d, 0xc1, 0x8e, 0x3c, 0x95, 0xb3, 0x3a, 0x81, 0x94, 0x1d, 0x76, 0xf3,
	0xa4, 0xe8, 0x95, 0x29, 0x3b, 0x75, 0x06, 0x6d, 0x76, 0x6b, 0xb2, 0xd8, 0x13, 0xa9, 0x09, 0xea,
	0x02, 0x32, 0x6d, 0x5c, 0xb4, 0x8c, 0x20, 0xf8, 0x3b, 0xed, 0xa6, 0x0e, 0xab, 0x85, 0xd5, 0x1c,
	0x3d, 0x61, 0x5f, 0x3e, 0xd9, 0x83, 0x5d, 0x67, 0x9e, 0xe6, 0x44, 0xe6, 0x99, 0x35, 0xc7, 0x80,
	0x83, 0xa6, 0xb3, 0x43, 0x76, 0x0b, 0xaf, 0xdd, 0xd1, 0x75, 0xd3, 0xfe, 0x34, 0x93, 0x65, 0xdc,
	0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x28, 0x23, 0xad, 0xb0, 0xa8, 0x01, 0x00, 0x00,
}
