// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wrap_request_znn.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WrapRequestZnnProto struct {
	NetworkType          uint32   `protobuf:"varint,1,opt,name=networkType,proto3" json:"networkType,omitempty"`
	ChainId              uint32   `protobuf:"varint,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ToAddress            string   `protobuf:"bytes,4,opt,name=toAddress,proto3" json:"toAddress,omitempty"`
	TokenAddress         string   `protobuf:"bytes,5,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	Amount               []byte   `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee                  []byte   `protobuf:"bytes,7,opt,name=fee,proto3" json:"fee,omitempty"`
	Signature            string   `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	Status               uint32   `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	SentSignature        bool     `protobuf:"varint,10,opt,name=sentSignature,proto3" json:"sentSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WrapRequestZnnProto) Reset()         { *m = WrapRequestZnnProto{} }
func (m *WrapRequestZnnProto) String() string { return proto.CompactTextString(m) }
func (*WrapRequestZnnProto) ProtoMessage()    {}
func (*WrapRequestZnnProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_e589c5a77ce52b4d, []int{0}
}

func (m *WrapRequestZnnProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrapRequestZnnProto.Unmarshal(m, b)
}
func (m *WrapRequestZnnProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrapRequestZnnProto.Marshal(b, m, deterministic)
}
func (m *WrapRequestZnnProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrapRequestZnnProto.Merge(m, src)
}
func (m *WrapRequestZnnProto) XXX_Size() int {
	return xxx_messageInfo_WrapRequestZnnProto.Size(m)
}
func (m *WrapRequestZnnProto) XXX_DiscardUnknown() {
	xxx_messageInfo_WrapRequestZnnProto.DiscardUnknown(m)
}

var xxx_messageInfo_WrapRequestZnnProto proto.InternalMessageInfo

func (m *WrapRequestZnnProto) GetNetworkType() uint32 {
	if m != nil {
		return m.NetworkType
	}
	return 0
}

func (m *WrapRequestZnnProto) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *WrapRequestZnnProto) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *WrapRequestZnnProto) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *WrapRequestZnnProto) GetTokenAddress() string {
	if m != nil {
		return m.TokenAddress
	}
	return ""
}

func (m *WrapRequestZnnProto) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *WrapRequestZnnProto) GetFee() []byte {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *WrapRequestZnnProto) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *WrapRequestZnnProto) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *WrapRequestZnnProto) GetSentSignature() bool {
	if m != nil {
		return m.SentSignature
	}
	return false
}

func init() {
	proto.RegisterType((*WrapRequestZnnProto)(nil), "events.WrapRequestZnnProto")
}

func init() { proto.RegisterFile("wrap_request_znn.proto", fileDescriptor_e589c5a77ce52b4d) }

var fileDescriptor_e589c5a77ce52b4d = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0x86, 0x53, 0x90, 0x65, 0x77, 0x84, 0xc4, 0x54, 0x43, 0xe6, 0xe0, 0xa1, 0x21, 0x1e, 0xf6,
	0x84, 0x07, 0x9f, 0x40, 0x6f, 0xde, 0x4c, 0x35, 0x31, 0xe1, 0x42, 0x2a, 0x3b, 0x2a, 0x21, 0x4e,
	0xd7, 0x76, 0x56, 0xa2, 0x2f, 0xe5, 0x2b, 0x9a, 0xed, 0x02, 0xc2, 0xad, 0xdf, 0x37, 0x7f, 0x67,
	0x26, 0x03, 0x93, 0x4d, 0x70, 0xf5, 0x22, 0xd0, 0x67, 0x43, 0x51, 0x16, 0x3f, 0xcc, 0xb3, 0x3a,
	0x78, 0xf1, 0x3a, 0xa3, 0x2f, 0x62, 0x89, 0xd3, 0xdf, 0x1e, 0x9c, 0x3f, 0x07, 0x57, 0xdb, 0x2e,
	0x31, 0x67, 0x7e, 0x48, 0x75, 0x03, 0xa7, 0x4c, 0xb2, 0xf1, 0x61, 0xfd, 0xf4, 0x5d, 0x13, 0x2a,
	0xa3, 0xca, 0xb1, 0x3d, 0x54, 0x1a, 0x61, 0xb8, 0x7c, 0x77, 0x2b, 0xbe, 0xaf, 0xb0, 0x97, 0xaa,
	0x3b, 0xd4, 0x17, 0x30, 0x60, 0xcf, 0x4b, 0xc2, 0xbe, 0x51, 0xe5, 0xc8, 0x76, 0xa0, 0x2f, 0xa1,
	0x10, 0x7f, 0x5b, 0x55, 0x81, 0x62, 0xc4, 0x13, 0xa3, 0xca, 0xc2, 0xfe, 0x0b, 0x3d, 0x85, 0x91,
	0xf8, 0x35, 0xf1, 0x2e, 0x30, 0x48, 0x81, 0x23, 0xa7, 0x27, 0x90, 0xb9, 0x0f, 0xdf, 0xb0, 0x60,
	0x96, 0x1a, 0x6f, 0x49, 0x9f, 0x41, 0xff, 0x95, 0x08, 0x87, 0x49, 0xb6, 0xcf, 0x76, 0x56, 0x5c,
	0xbd, 0xb1, 0x93, 0x26, 0x10, 0xe6, 0xdd, 0xac, 0xbd, 0x68, 0xfb, 0x44, 0x71, 0xd2, 0x44, 0x2c,
	0xd2, 0xe2, 0x5b, 0xd2, 0x57, 0x30, 0x8e, 0xc4, 0xf2, 0xb8, 0xff, 0x09, 0x46, 0x95, 0xb9, 0x3d,
	0x96, 0x77, 0x30, 0xcf, 0x67, 0xd7, 0xdd, 0xf5, 0x5e, 0xb2, 0x74, 0xcc, 0x9b, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x18, 0x8e, 0xa3, 0x53, 0x66, 0x01, 0x00, 0x00,
}
